update GH workflows

diff --git a/.github/workflows/build_status.yml b/.github/workflows/build_status.yml
--- a/.github/workflows/build_status.yml
+++ b/.github/workflows/build_status.yml
@@ -2,23 +2,24 @@ name: Build Status
 
 on:
   push:
-    branches:
-      - '*'
+    branches: [ '*' ]
   pull_request:
+
+env:
+  JAVA_VERSION: 21
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Set up JDK 21
+      - name: Set up JDK ${{ env.JAVA_VERSION }}
         uses: actions/setup-java@v4
         with:
+          java-version: ${{ env.JAVA_VERSION }}
           distribution: 'microsoft'
-          java-version: 21
-          cache: 'gradle'
-      - name: Validate Gradle Wrapper
-        uses: gradle/actions/wrapper-validation@v4
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
       - name: Build with Gradle
@@ -49,3 +50,8 @@ jobs:
             !NeoForge/build/libs/*-dev.jar
       - name: Run tests
         run: ./gradlew check
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@ee6b445351cd81e2f73a16a0e52d598aeac2197f # v5.3.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
